import type { LineQty, Product, Shop } from "./types";

export const KHR_PER_USD = 4100;
export const VOLUME_CASE_THRESHOLD = 5;
export const VOLUME_RATE = 0.02;
export const DEPOT = {
  nameKm: "ដេប៉ូភូមិព្រែកលៀប",
  nameEn: "Prek Lieb Depot",
  provinceKm: "ខេត្តកំពង់ចាម",
  routeKm: "ផ្លូវ RC-07 ផ្លូវទន្លេ",
  routeEn: "River road RC-07",
  driverKm: "សុខ បញ្ញា",
  driverEn: "Sok Panha",
  helperKm: "ចាន់ ដារ៉ា",
  plate: "2A-8842",
  van: "Toyota Hiace",
  printer: "RPP02N Belt",
  merchant: "PREK LIEB DEPOT",
  phone: "042 941 220",
};

const q = (crate = 0, pack = 0, single = 0): LineQty => ({ single, pack, crate });

export const PRODUCTS: Product[] = [
  {
    id: "angkor",
    sku: "ANK-330",
    nameKm: "ស្រាបៀរអង្គរ",
    nameEn: "Angkor Beer 330ml",
    category: "beer",
    unitSingleKm: "កំប៉ុង",
    unitPackKm: "វេច",
    unitCrateKm: "កេស",
    packPieces: 6,
    cratePieces: 24,
    priceSingle: 70,
    pricePack: 390,
    priceCrate: 1480,
  },
  {
    id: "cambodia",
    sku: "CBB-330",
    nameKm: "ស្រាបៀរកម្ពុជា",
    nameEn: "Cambodia Beer 330ml",
    category: "beer",
    unitSingleKm: "កំប៉ុង",
    unitPackKm: "វេច",
    unitCrateKm: "កេស",
    packPieces: 6,
    cratePieces: 24,
    priceSingle: 65,
    pricePack: 360,
    priceCrate: 1360,
  },
  {
    id: "vital",
    sku: "VIT-500",
    nameKm: "ទឹកសុទ្ធ Vital",
    nameEn: "Vital Water 500ml",
    category: "beverage",
    unitSingleKm: "ដប",
    unitPackKm: "វេច",
    unitCrateKm: "កេស",
    packPieces: 12,
    cratePieces: 24,
    priceSingle: 25,
    pricePack: 220,
    priceCrate: 400,
  },
  {
    id: "sting",
    sku: "STG-330",
    nameKm: "ស្ទីងក្រហម",
    nameEn: "Sting Red 330ml",
    category: "beverage",
    unitSingleKm: "ដប",
    unitPackKm: "វេច",
    unitCrateKm: "ថាស",
    packPieces: 6,
    cratePieces: 24,
    priceSingle: 45,
    pricePack: 240,
    priceCrate: 880,
  },
  {
    id: "coke",
    sku: "COK-330",
    nameKm: "កូកា-កូឡា",
    nameEn: "Coca-Cola 330ml",
    category: "beverage",
    unitSingleKm: "កំប៉ុង",
    unitPackKm: "វេច",
    unitCrateKm: "កេស",
    packPieces: 6,
    cratePieces: 24,
    priceSingle: 50,
    pricePack: 270,
    priceCrate: 1020,
  },
  {
    id: "mama",
    sku: "MMA-PRK",
    nameKm: "មីម៉ាម៉ា សាច់ជ្រូក",
    nameEn: "Mama noodles pork",
    category: "grocery",
    unitSingleKm: "កញ្ចប់",
    unitPackKm: "វេច",
    unitCrateKm: "កេស",
    packPieces: 5,
    cratePieces: 30,
    priceSingle: 22,
    pricePack: 100,
    priceCrate: 540,
  },
  {
    id: "fish",
    sku: "FSH-700",
    nameKm: "ទឹកត្រីខ្មែរ",
    nameEn: "Khmer fish sauce 700ml",
    category: "grocery",
    unitSingleKm: "ដប",
    unitPackKm: "វេច",
    unitCrateKm: "កេស",
    packPieces: 6,
    cratePieces: 12,
    priceSingle: 115,
    pricePack: 640,
    priceCrate: 1200,
  },
  {
    id: "oil",
    sku: "OIL-1L",
    nameKm: "ប្រេងឆហង្ស",
    nameEn: "Hong cooking oil 1L",
    category: "grocery",
    unitSingleKm: "ដប",
    unitPackKm: "វេច",
    unitCrateKm: "កេស",
    packPieces: 3,
    cratePieces: 12,
    priceSingle: 180,
    pricePack: 510,
    priceCrate: 1920,
  },
];

/** Morning cage load, in base pieces. */
export const MORNING_LOAD: Record<string, number> = {
  angkor: 48 * 24,
  cambodia: 30 * 24,
  vital: 40 * 24,
  sting: 24 * 24,
  coke: 24 * 24,
  mama: 20 * 30,
  fish: 18 * 12,
  oil: 16 * 12,
};

export const SHOPS: Shop[] = [
  {
    id: "mom",
    nameKm: "ហាងអ៊ុំស្រីមុំ",
    nameEn: "Aunt Srey Mom",
    ownerKm: "អ៊ុំ ស្រីមុំ",
    phone: "012 884 219",
    areaKm: "ភូមិព្រែកលៀប · មុខផ្សារ",
    minutesFromPrev: 6,
    mapX: 58,
    mapY: 168,
    tradePct: 2,
    creditLimit: 8000,
    baseOutstanding: 0,
    usual: { angkor: q(2), vital: q(1), mama: q(2) },
  },
  {
    id: "vireak",
    nameKm: "តូបបងវិរៈ",
    nameEn: "Bong Vireak stall",
    ownerKm: "បង វិរៈ",
    phone: "010 332 441",
    areaKm: "មាត់ទន្លេ · ខាងសាលារៀន",
    minutesFromPrev: 8,
    mapX: 96,
    mapY: 132,
    tradePct: 3,
    creditLimit: 15000,
    baseOutstanding: 1800,
    usual: { angkor: q(3), sting: q(2), fish: q(1), oil: q(1) },
  },
  {
    id: "prek",
    nameKm: "ផ្សារព្រែកលៀប",
    nameEn: "Prek Lieb market",
    ownerKm: "លោក ហេង",
    phone: "011 778 903",
    areaKm: "ផ្សារព្រែកលៀប · ទូរទី ៤",
    minutesFromPrev: 7,
    mapX: 138,
    mapY: 156,
    tradePct: 3,
    creditLimit: 20000,
    baseOutstanding: 2400,
    usual: { angkor: q(2), vital: q(2), coke: q(1), mama: q(1) },
  },
  {
    id: "lyhuor",
    nameKm: "ហាងលីហួរ",
    nameEn: "Ly Huor grocery",
    ownerKm: "លី ហួរ",
    phone: "097 552 180",
    areaKm: "ផ្លូវជាតិលេខ ៧ · គីឡូ ៣",
    minutesFromPrev: 11,
    mapX: 176,
    mapY: 108,
    tradePct: 4,
    creditLimit: 30000,
    baseOutstanding: 0,
    usual: { angkor: q(4), cambodia: q(2), vital: q(3), coke: q(1), oil: q(1) },
  },
  {
    id: "mao",
    nameKm: "តូបអ្នកស្រីម៉ៅ",
    nameEn: "Neak Srey Mao",
    ownerKm: "អ្នកស្រី ម៉ៅ",
    phone: "012 409 775",
    areaKm: "ភូមិកោះប៉ែន · មាត់ផ្លូវលូ",
    minutesFromPrev: 9,
    mapX: 214,
    mapY: 142,
    tradePct: 0,
    creditLimit: 5000,
    baseOutstanding: 600,
    usual: { vital: q(0, 2), sting: q(0, 3), mama: q(0, 4), coke: q(0, 2) },
  },
  {
    id: "hoeun",
    nameKm: "ហាងសុខហ៊ាន",
    nameEn: "Sok Hoeun shop",
    ownerKm: "សុខ ហ៊ាន",
    phone: "010 918 334",
    areaKm: "ភូមិអូរម្អម · ជិតវត្ត",
    minutesFromPrev: 12,
    mapX: 248,
    mapY: 92,
    tradePct: 2,
    creditLimit: 10000,
    baseOutstanding: 7800,
    usual: { angkor: q(2), cambodia: q(1), fish: q(1), mama: q(1) },
  },
  {
    id: "kilo5",
    nameKm: "តូបគីឡូប្រាំ",
    nameEn: "Kilo 5 stall",
    ownerKm: "អ៊ុំ ណារី",
    phone: "011 220 648",
    areaKm: "ផ្លូវជាតិលេខ ៧ · គីឡូ ៥",
    minutesFromPrev: 8,
    mapX: 286,
    mapY: 124,
    tradePct: 1,
    creditLimit: 8000,
    baseOutstanding: 0,
    usual: { vital: q(2), sting: q(1), mama: q(1), coke: q(0, 2) },
  },
  {
    id: "pisith",
    nameKm: "ហាងពិសិដ្ឋ",
    nameEn: "Pisith shop",
    ownerKm: "ពិសិដ្ឋ",
    phone: "012 663 091",
    areaKm: "ផ្សារស្ពានដែក · ខាងជើង",
    minutesFromPrev: 10,
    mapX: 318,
    mapY: 78,
    tradePct: 3,
    creditLimit: 25000,
    baseOutstanding: 4200,
    usual: { angkor: q(3), cambodia: q(2), vital: q(2), oil: q(1), fish: q(1) },
  },
  {
    id: "spean",
    nameKm: "ផ្សារស្ពានដែក",
    nameEn: "Spean Daek market",
    ownerKm: "ហាងរួម សុភា",
    phone: "097 441 228",
    areaKm: "ផ្សារស្ពានដែក · ទូរកណ្តាល",
    minutesFromPrev: 6,
    mapX: 352,
    mapY: 116,
    tradePct: 5,
    creditLimit: 40000,
    baseOutstanding: 6500,
    usual: { angkor: q(6), cambodia: q(3), vital: q(4), coke: q(2), mama: q(2), oil: q(1) },
  },
  {
    id: "oumom",
    nameKm: "ហាងចុងផ្លូវអូរម្អម",
    nameEn: "Ou Mom end shop",
    ownerKm: "យាយ ស៊ីន",
    phone: "010 775 012",
    areaKm: "ចុងផ្លូវ RC-07 · មុខស្ពានឈើ",
    minutesFromPrev: 14,
    mapX: 378,
    mapY: 64,
    tradePct: 2,
    creditLimit: 12000,
    baseOutstanding: 1500,
    usual: { angkor: q(1), vital: q(1), mama: q(1), fish: q(0, 1), sting: q(0, 2) },
  },
];

export const PRODUCT_MAP = Object.fromEntries(PRODUCTS.map((p) => [p.id, p]));
export const SHOP_MAP = Object.fromEntries(SHOPS.map((s) => [s.id, s]));

export function emptyQty(): LineQty {
  return { single: 0, pack: 0, crate: 0 };
}
